TRUNCATE TABLE
  horarios,
  paralelos,
  prerequisitos,
  plan_estudio,
  electivas,
  tecnico_superior,
  requisitos_beca,
  becas,
  requisitos_ingreso,
  modalidades_ingreso,
  enlaces,
  contacto,
  materias,
  docentes,
  aulas,
  edificios,
  menciones,
  autoridades,
  info_institucional,
  objetivos,
  carrera,
  telegram_sessions
RESTART IDENTITY CASCADE;
